webserver:
  port: 3020
database:
  mysql:
    host: ""
    port: 3306
    username: ""
    password: ""
    database: ""
    # 时间配置单位s
    maxPoolSize: 16
    idleTimeout: 30
    connectionTimeout: 2
    maxLifetime: 1800
    maxWaitQueueSize: 5000

vertx:
  verticle: com.vertx.example.verticle.MainVerticle
  instances: 1
  ha: true

webclient:
  maxPoolSize: 16
  connectTimeout: 2000
  readIdleTimeout: 20000
  idleTimeout: 10000
  writeIdleTimeout: 10000
